### PR TITLE
Feature/fix mac os build

### PR DESCRIPTION
**Pull request by Lutzifer**

### CODE REVIEW

**Comment by roberthein** [comment]
Thanks @Lutzifer! I merged all of it, only had to tweak some small things to let it keep working for Cocoapods.
Also TinyConstraints is now using `UIEdgeInsets` instead of `CGFloat` for `edgesToSuperview`.
✌️

**Comment by roberthein** [comment]
If you don't like to have something like `UIEdgeInsets(top: margin, left: margin, bottom: margin, right: margin)`, you could consider creating an extension on `UIEdgeInsets` that makes it shorter, like:
```
extension UIEdgeInsets {
    static var equalInsets(_ margin: CGFloat) -> UIEdgeInsets {
        return UIEdgeInsets(top: margin, left: margin, bottom: margin, right: margin)
    }
}
```
🤷‍♂️

**Comment by Lutzifer** [comment]
Yeah, that's another way to do it. Could we include it directly?
We should consider the overall use of insets in the lib (see https://github.com/roberthein/TinyConstraints/pull/31).

**Comment by rudedogg** [comment]
Should the podspec have a macOS target?

**Pull request merged**
