### PR TITLE
Added support for Swift 4.2

### PR DESCRIPTION
**Pull request by timedwardsios**

### CODE REVIEW

**Comment by alexanderkhitev** [comment]
Hey @roberthein could you approve this pr?

**Comment by roberthein** [comment]
There is a Swift 4.2 brach now. 👌
`pod 'TinyConstraints', :git => 'https://github.com/roberthein/TinyConstraints.git', :branch => 'release/Swift-4.2'`

**Comment by alexanderkhitev** [comment]
@roberthein thank you so much! One question, do you plan to merge it in master branch?

**Comment by roberthein** [comment]
Oh yeah sure, do you use Carthage @alexanderkhitev?

**Comment by alexanderkhitev** [comment]
@roberthein no, I use pods

**Pull request merged**
