### PR TITLE
Xcode 10.2 and Swift 5 support

### PR DESCRIPTION
**Pull request by onurgenes**

### CODE REVIEW

**Comment by roberthein** [comment]
Awesome @onurgenes! 🙏 I'm merging this asap..

**Comment by onurgenes** [comment]
Thank you so much for fast reply and this beautiful repo! Just check it out before merging for any issues.

Thanks in advance.

**Comment by roberthein** [comment]
Of course! I just updated Xcode ;)

**Comment by onurgenes** [comment]
Also I forgot to update PodSpecs 😅. Sorry...

**Comment by roberthein** [comment]
Hehe, down't worry..

**Comment by onurgenes** [comment]
I think we should update .swiftversion and PodSpecs too. Should I update them?

**Comment by roberthein** [comment]
I'm on it!

**Comment by roberthein** [comment]
It's up! Thanks again @onurgenes ❤️

**Comment by onurgenes** [comment]
Cheers 🎉

**Pull request merged**
